### ISSUE TITLE
good for three-way admixed population?

### ISSUE THREAD

**Issue by complexgenome** [priyamoorjani/rolloff#1]
Dear Dr. Priya,

The documentation mentions for two ancestral population along with the paper (The History of African Gene Flow into Southern Europeans, Levantines, and Jews). 
Populations such as Caribbean Hispanics are three-way admixed, is rolloff a good tool to use for them?

Thank you.

**Comment by priyamoorjani** [comment]
Thanks for the query. Rolloff is mainly designed for dating two-way
population mixture. If you are interested in multi-way mixture, perhaps you
can try MALDER or other methods that explicitly model multi-way population
mixtures.

**Comment by complexgenome** [comment]
Nice, alder is next on my list along with fastStructure of tools to explore. :) 
https://github.com/joepickrell/malder/tree/master/MALDER

Thank you.
